stages:
  - build-api
  - deploy-local
  # - deploy-homolog
  # - deploy-prod

Gerando imagem Docker api:
  stage: build-api
  script:
    - docker build . --tag node-api:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - shell

Deploy API em DEV:
  stage: deploy-local
  variables:
    TAG: $CI_COMMIT_TAG
    URL: http://127.0.0.1:3000/deploy
    HEADER: 'Content-Type: application/x-www-form-urlencoded'
  script:
    - docker stack deploy --compose-file=./dev/server.yml api-dev
    - curl -X POST "${URL}" -H "${HEADER}" --data-urlencode '{"Componente":Deploy-app-front}' --data-urlencode '{"Versão":"${TAG}"}'
  only:
    - tags
  tags:
    - shell
