stages:
  - build-api
  - deploy-local
  # - deploy-homolog
  # - deploy-prod

Gerando imagem Docker api:
  stage: build-api
  script:
    - docker build . --tag node-api:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - shell

Deploy API em DEV:
  stage: deploy-local
  script:
    - docker stack deploy --compose-file=./dev/server.yml api-dev
  only:
    - tags
  tags:
    - shell
