stages:
  - deploy-local
  # - deploy-homolog
  # - deploy-prod

Deploy Portainer em Local:
  stage: deploy-local
  allow_failure: true
  script:
    - docker stack deploy --compose-file=./dev/portainer.yml api-dev
  when: manual
  tags:
    - local-shell

Deploy API em DEV:
  stage: deploy-local
  allow_failure: true
  script:
    - docker stack deploy --compose-file=./dev/server.yml api-dev
  when: manual
  tags:
    - local-shell
