stages:
  - build-api
  - deploy-local
  # - deploy-homolog
  # - deploy-prod

    TAG: $CI_COMMIT_TAG
    URL: http://127.0.0.1:3000/deploy
    CONTENT: 'Content-Type: application/json'

Gerando imagem Docker api:
  stage: build-api
  script:
    - docker build . --tag node-api:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - shell

Deploy API em DEV:
  stage: deploy-local
  script:
    - docker stack deploy --compose-file=./dev/server.yml api-dev
    - curl -X POST "${URL}" -H "${CONTENT}" --data-urlencode '{"Componente":Deploy-app-front}' --data-urlencode '{"Versao":\"${TAG}\"}' --data-urlencode '{"Responsavel":Rodolfo}'
  only:
    - tags
  tags:
    - shell
