version: '3.4'

services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    networks:
      - api-net
    volumes:
      - '/opt/mongodb:/data/db'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1m
        order: start-first

networks:
  api-net:
    external:
      name: api-net
