version: "3.4"
services:
  portainer:
    image: portainer/portainer
    networks:
      - api-net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
    ports:
       - "9000:9000"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
   portainerdata:

networks:
  api-net:
    external:
      name: api-net
