version: '3.4'

services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    networks:
      - api-net
    volumes:
      - '/opt/mongodb:/data/db'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1m
        order: start-first
  api:
    image: node-api:$CI_COMMIT_TAG
    networks:
      - api-net
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first

networks:
  api-net:
    external:
      name: api-net
